version: '3.9'

services:
  realhub_ai_auth_service:
    build: ./auth_service
    ports:
      - "8000:8000"
    volumes:
      - ./auth_service:/app
    env_file:
      - ./auth_service/.env
    depends_on:
      - db_auth
    networks:
      - app-network
  realhub_ai_post_service:
    build: ./post_service
    ports:
      - "8081:8081"
    volumes:
      - ./post_service:/app
    env_file:
      - ./post_service/.env
    depends_on:
      - db_post
    networks:
      - app-network
  
  realhub_ai_api_service:
    build: ./api_service
    ports:
      - "8082:8082"
    volumes:
      - ./api_service:/app
    env_file:
      - ./api_service/.env
    depends_on:
      - db_api
    networks:
      - app-network

  db_auth:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: realhub_ai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - pgdata_auth:/var/lib/postgresql/data
    networks:
      - app-network
  db_post:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: realhub_ai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - pgdata_post:/var/lib/postgresql/data
    networks:
      - app-network
  db_api:
    image: postgres:15
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: realhub_ai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - pgdata_api:/var/lib/postgresql/data
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  
  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.0
    container_name: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5044:5044"  
      - "9600:9600"  
    depends_on:
      - elasticsearch
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.10.0
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./auth_service/logs:/var/log/fastapi/auth:ro
      - ./post_service/logs:/var/log/fastapi/post:ro
      - ./api_service/logs:/var/log/fastapi/api:ro
    command: ["--strict.perms=false"]
    depends_on:
      - logstash
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535


volumes:
  pgdata_auth:
  pgdata_post:
  pgdata_api:
  esdata:

networks:
  app-network:
    driver: bridge

