from sqlalchemy import Column, Integer, String, DateTime, Boolean, ForeignKey, Text, Enum
from sqlalchemy.sql import func
from database import Base
class Message(Base):
    __tablename__ = 'Wo_Messages'
    
    id = Column(Integer, primary_key=True, index=True)
    from_id = Column(Integer, ForeignKey('Wo_Users.user_id'), index=True)
    group_id = Column(Integer, default=0)
    page_id = Column(Integer, default=0)
    to_id = Column(Integer, ForeignKey('Wo_Users.user_id'), index=True)
    text = Column(Text)
    media = Column(String(255), default='')
    mediaFileName = Column(String(200), default='')
    mediaFileNames = Column(String(200), default='')
    time = Column(Integer, default=0)
    seen = Column(Integer, default=0)
    deleted_one = Column(Enum('0', '1'), default='0')
    deleted_two = Column(Enum('0', '1'), default='0')
    sent_push = Column(Integer, default=0)
    notification_id = Column(String(50), default='')
    type_two = Column(String(32), default='')
    stickers = Column(Text)
    product_id = Column(Integer, default=0)
    property_id = Column(Integer, default=0)
    podcast_id = Column(Integer, default=0)
    poll_id = Column(Integer, default=0)
    lat = Column(String(200), default='0')
    lng = Column(String(200), default='0')
    reply_id = Column(Integer, default=0)
    story_id = Column(Integer, default=0)
    broadcast_id = Column(Integer, default=0)
    forward = Column(Integer, default=0)
    listening = Column(Integer, default=0)
    remove_at = Column(Integer, default=0)