from sqlalchemy import Column, Integer, String, DateTime, Boolean, ForeignKey, Text, Float, JSON, Enum
from sqlalchemy.sql import func
from database import Base

class User(Base):
    __tablename__ = 'Wo_Users'
    
    user_id = Column(Integer, primary_key=True, index=True)
    username = Column(String(32), unique=True, index=True)
    email = Column(Text, unique=True, index=True)
    password = Column(String(70))
    first_name = Column(String(60))
    last_name = Column(String(32))
    avatar = Column(Text)
    cover = Column(String(100), default='upload/photos/d-cover.jpg')
    background_image = Column(String(100), default='')
    background_image_status = Column(Enum('0', '1'), default='0')
    relationship_id = Column(Integer, default=0)
    address = Column(String(100))
    working = Column(String(32), default='')
    working_link = Column(String(32), default='')
    about = Column(Text)
    school = Column(String(32), default='')
    gender = Column(String(32), default='2556')
    birthday = Column(String(50), default='0000-00-00')
    country_id = Column(Integer, default=0)
    website = Column(Text)
    facebook = Column(Text)
    google = Column(String(50), default='')
    twitter = Column(String(50), default='')
    linkedin = Column(Text)
    youtube = Column(String(100), default='')
    vk = Column(String(32), default='')
    instagram = Column(String(32), default='')
    qq = Column(Text)
    wechat = Column(Text)
    discord = Column(Text)
    mailru = Column(Text)
    okru = Column(String(30), default='')
    language = Column(String(31), default='english')
    email_code = Column(String(32), default='')
    src = Column(String(32), default='Undefined')
    ip_address = Column(String(100), default='')
    follow_privacy = Column(Enum('1', '0'), default='0')
    friend_privacy = Column(Enum('0', '1', '2', '3'), default='0')
    post_privacy = Column(String(255), default='ifollow')
    message_privacy = Column(Enum('1', '0', '2'), default='0')
    confirm_followers = Column(Enum('1', '0'), default='0')
    show_activities_privacy = Column(Enum('0', '1'), default='1')
    birth_privacy = Column(Enum('0', '1', '2'), default='0')
    visit_privacy = Column(Enum('0', '1'), default='0')
    verified = Column(Enum('1', '0'), default='0')
    lastseen = Column(Integer, default=0)
    showlastseen = Column(Enum('1', '0'), default='1')
    emailNotification = Column(Enum('1', '0'), default='1')
    e_liked = Column(Enum('0', '1'), default='1')
    e_wondered = Column(Enum('0', '1'), default='1')
    e_shared = Column(Enum('0', '1'), default='1')
    e_followed = Column(Enum('0', '1'), default='1')
    e_commented = Column(Enum('0', '1'), default='1')
    e_visited = Column(Enum('0', '1'), default='1')
    e_liked_page = Column(Enum('0', '1'), default='1')
    e_mentioned = Column(Enum('0', '1'), default='1')
    e_joined_group = Column(Enum('0', '1'), default='1')
    e_accepted = Column(Enum('0', '1'), default='1')
    e_profile_wall_post = Column(Enum('0', '1'), default='1')
    e_sentme_msg = Column(Enum('0', '1'), default='0')
    e_last_notif = Column(String(50), default='0')
    notification_settings = Column(String(400), default='{"e_liked":1,"e_shared":1,"e_wondered":0,"e_commented":1,"e_followed":1,"e_accepted":1,"e_mentioned":1,"e_joined_group":1,"e_liked_page":1,"e_visited":1,"e_profile_wall_post":1,"e_memory":1}')
    status = Column(Enum('1', '0'), default='0')
    active = Column(Enum('0', '1', '2'), default='0')
    admin = Column(Enum('0', '1', '2'), default='0')
    type = Column(String(11), default='user')
    registered = Column(String(32), default='0/0000')
    start_up = Column(Enum('0', '1'), default='0')
    start_up_info = Column(Enum('0', '1'), default='0')
    start_up_profile_select = Column(Integer, default=0)
    start_up_property_links = Column(Integer, default=0)
    start_up_connect_integrations_realHub = Column(Integer, default=0)
    start_up_connect_integrations_crm = Column(Integer, default=0)
    start_up_connect_others = Column(Integer, default=0)
    startup_property_listings = Column(Integer, default=0)
    startup_consent_screen = Column(Integer, default=0)
    startup_follow = Column(Enum('0', '1'), default='0')
    startup_image = Column(Enum('0', '1'), default='0')
    last_email_sent = Column(Integer, default=0)
    phone_number = Column(Text)
    sms_code = Column(Integer, default=0)
    is_pro = Column(Enum('0', '1'), default='0')
    pro_time = Column(Integer, default=0)
    pro_type = Column(Integer, default=0)
    pro_remainder = Column(String(20), default='')
    joined = Column(Integer, default=0)
    css_file = Column(String(100), default='')
    timezone = Column(String(50), default='')
    referrer = Column(Integer, default=0)
    ref_user_id = Column(Integer, default=0)
    ref_level = Column(Text)
    balance = Column(String(100), default='0')
    paypal_email = Column(String(100), default='')
    notifications_sound = Column(Enum('0', '1'), default='0')
    order_posts_by = Column(Enum('0', '1'), default='1')
    social_login = Column(Enum('0', '1'), default='0')
    android_m_device_id = Column(String(50), default='')
    ios_m_device_id = Column(String(50), default='')
    android_n_device_id = Column(String(50), default='')
    ios_n_device_id = Column(String(50), default='')
    web_device_id = Column(String(100), default='')
    wallet = Column(String(20), default='0.00')
    lat = Column(String(200), default='0')
    initial_latitude = Column(String(200), default='0')
    lng = Column(String(200), default='0')
    initial_longitude = Column(String(200), default='0')
    last_location_update = Column(String(30), default='0')
    share_my_location = Column(Integer, default=1)
    last_data_update = Column(Integer, default=0)
    details = Column(String(300), default='{"post_count":0,"album_count":0,"following_count":0,"followers_count":0,"groups_count":0,"likes_count":0}')
    sidebar_data = Column(Text)
    last_avatar_mod = Column(Integer, default=0)
    last_cover_mod = Column(Integer, default=0)
    points = Column(Float, default=0)
    daily_points = Column(Integer, default=0)
    converted_points = Column(Float, default=0)
    point_day_expire = Column(String(50), default='')
    last_follow_id = Column(Integer, default=0)
    share_my_data = Column(Integer, default=1)
    last_login_data = Column(Text)
    two_factor = Column(Integer, default=0)
    two_factor_hash = Column(String(50), default='')
    new_email = Column(String(255), default='')
    two_factor_verified = Column(Integer, default=0)
    new_phone = Column(String(32), default='')
    info_file = Column(String(300), default='')
    city = Column(String(50))
    state = Column(String(50))
    zip = Column(String(11))
    school_completed = Column(Integer, default=0)
    weather_unit = Column(String(11), default='us')
    paystack_ref = Column(String(100), default='')
    code_sent = Column(Integer, default=0)
    time_code_sent = Column(Integer, default=0)
    permission = Column(Text)
    skills = Column(Text)
    languages = Column(Text)
    currently_working = Column(String(50), default='')
    banned = Column(Integer, default=0)
    banned_reason = Column(Text)
    credits = Column(Float, default=0)
    authy_id = Column(String(100), default='')
    google_secret = Column(String(100), default='')
    two_factor_method = Column(String(50), default='two_factor')
    phone_privacy = Column(Enum('0', '1', '2'), default='0')
    stripe_customer_id = Column(Text)
    stripe_card_id = Column(Text)
    realtor_profile_url = Column(Text)
    country_name = Column(String(250))
    my_profession = Column(Text)
    startup_first_post = Column(Integer, default=0)
    zillow_username = Column(Text)
    realtor_username = Column(Text)
    realtor_ca_profile = Column(String(250))
    accept_property_terms = Column(Integer, default=0)
    set_invoice_address = Column(String(250))
    profile_url = Column(Text)
    organization_name = Column(Text)
    pending = Column(Text)
    experience = Column(Text)
    description = Column(Text)
    recommendations_count = Column(Text)
    for_sale_count = Column(Text)
    for_sale_min = Column(Text)
    for_sale_max = Column(Text)
    recently_sold_count = Column(Text)
    recently_sold_min = Column(Text)
    recently_sold_max = Column(Text)
    office = Column(Text)
    mobile = Column(Text)
    fax = Column(Text)
    job_title = Column(Text)
    agency_name = Column(Text)
    email_2 = Column(Text)
    association = Column(Text)
    license_number = Column(Text)
    office_name = Column(Text)
    office_city = Column(Text)
    office_state_code = Column(Text)
    office_state = Column(Text)
    office_postal_code = Column(Text)
    specialty = Column(Text)
    office_address1 = Column(Text)
    office_address2 = Column(Text)
    office_zip = Column(Text)
    office_county = Column(Text)
    office_phone = Column(Text)
    office_fax = Column(Text)
    faxnumber = Column(Text)
    facebook_access_token = Column(Text)
    google_access_token = Column(Text, default='')
    linkedin_access_token = Column(Text)
    linkedin_urn_token = Column(String(255))
    linkedin_business_access_token = Column(Text)
    linkedin_business_urn_token = Column(Text)
    zoom_access_token = Column(Text)
    outlook_access_token = Column(Text)
    facebook_selected_pages = Column(Text)
    linkedin_selected_pages = Column(Text)
    sso_token = Column(Text)
    twitter_access_token = Column(Text)
    twitter_access_token_secret = Column(Text)
    matchedUser_id = Column(String(255), default='0')
    full_address = Column(String(255))
    office_cell_phone = Column(String(255))
    office_country = Column(String(255))
    search_count = Column(Integer)
    search_reset_time = Column(DateTime, server_default=func.now())
    like_reset_time = Column(DateTime, server_default=func.now())
    like_count = Column(Integer)
    comment_reset_time = Column(DateTime, server_default=func.now())
    comment_count = Column(Integer, default=0)
    follow_reset_time = Column(DateTime, server_default=func.now())
    follow_count = Column(Integer, default=0)
    msg_noti_tone = Column(Integer, default=1)
    disabled_notification = Column(Integer, default=1)
    is_online = Column(Integer, default=1)
    with_email = Column(Integer, default=0)
    postPrivacy = Column(Integer, default=0)
    agency_logo = Column(Text)
    trial = Column(Integer, default=1)
    trial_period = Column(DateTime, server_default=func.now())
    trial_modal = Column(DateTime)
    beta_banner_status = Column(Integer, default=0)
    beta_banner = Column(DateTime)
    have_monetization = Column(Integer, default=0)
    unipile_google_account_id = Column(Text)
    unipile_outlook_account_id = Column(Text)
    unipile_imap_account_id = Column(Text)
    ayrshare_ref_id = Column(Text)
    ayrshare_profile_id = Column(Text)
    ayrshare_facebook_connected = Column(Integer, default=0)
    ayrshare_instagram_connected = Column(Integer, default=0)